/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { UseOfLanguageQuestionType } from '@src/app/enums/use-of-language-question-type';

export class InstructionGridModel {
    id: number;
    text: string;
    questionType: UseOfLanguageQuestionType;
    language: string;
}