/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { HttpClient, HttpParams, HttpResponse } from '@angular/common/http';
import { Inject, Injectable } from '@angular/core';
import { AugurEntityController, AugurHttpRequest, IAugurHttpRequest } from '@augur';
import { Tenant } from '@platform/entities/tenant';

@Injectable({
    providedIn: 'root'
})
export class TenantsController extends AugurEntityController<Tenant> {

    constructor(protected http: HttpClient, @Inject('BASE_URL')protected baseUrl: string) {
        super('api/tenants', http, baseUrl);
        
        this.listForGridFilter = this.listForGridFilter.bind(this);
    }
    
    listForGridFilter(pageNumber: number, pageSize: number, searchQuery: string, columnFilter: any): AugurHttpRequest<HttpResponse<any[]>> {
        const queryParams = new HttpParams()
            .set('pageNumber', pageNumber ? pageNumber.toString() : '')
            .set('pageSize', pageSize ? pageSize.toString() : '')
            .set('searchQuery', searchQuery ? searchQuery.toString() : '');
        
        return this.http.post(this.baseUrl + this.controllerRoute + `/listForGridFilter`, columnFilter ? columnFilter : {}, { params: queryParams, observe: 'response' })
            .toAugurHttpRequest<HttpResponse<any[]>>();
    }
}