/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { PermissionModel } from '@platform/models/permission-model';

export class LoggedInUserInfoModel {
    id: number;
    email: string;
    name: string;
    isActive: boolean;
    hasVerifiedEmail: boolean;
    isSuperAdmin: boolean;
    permissions: PermissionModel[];
    roleId: number;
    isOrgAdmin: boolean;
}