/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { LoggedInUserInfoModel } from '@platform/models/logged-in-user-info-model';

export class SignInResponseModel {
    token: string;
    user: LoggedInUserInfoModel;
}