using System.IO;
using Augur.BackendToFrontendExporter.Extensions;

namespace Augur.BackendToFrontendExporter
{
    public class FileAutoGen : AutoGenComponent
    {
        public FileAutoGen(string text, params string[] pathComponents)
        {
            this.FilePath = Path.Combine(pathComponents);
            this.Text = text;
        }

        public string FilePath { get; }
        public string Text { get; }

        private readonly string autogenText = @"
            /*
                This is an autogenerated file.
                Remove this comment if you don't want your changes to this file to be overwritten.
            */
        ".ProcessTemplate();

        public override void Execute()
        {
            if (!Directory.Exists(Path.GetDirectoryName(this.FilePath)))
            {
                Directory.CreateDirectory(Path.GetDirectoryName(this.FilePath));
            }

            if (File.Exists(this.FilePath))
            {
                var text = File.ReadAllText(this.FilePath);

                if (text.Contains(this.autogenText))
                {
                    File.WriteAllText(this.FilePath, $"{this.autogenText}\r\n{this.Text}");
                }
                else
                {
                    return;
                }
            }
            else
            {
                File.WriteAllText(this.FilePath, $"{this.autogenText}\r\n{this.Text}");
            }
        }
    }
}