/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { HttpClient, HttpParams, HttpResponse } from '@angular/common/http';
import { Inject, Injectable } from '@angular/core';
import { AugurHttpRequest, IAugurHttpRequest } from '@augur';


@Injectable({
    providedIn: 'root'
})
export class FilesController {

    constructor(protected http: HttpClient, @Inject('BASE_URL')protected baseUrl: string) {
        
        this.upload = this.upload.bind(this);
        this.uploadImageAndResize = this.uploadImageAndResize.bind(this);
        this.uploadAudio = this.uploadAudio.bind(this);
    }

    controllerRoute: string = 'api/files';
    
    upload(): IAugurHttpRequest {
        
        return this.http.post(this.baseUrl + this.controllerRoute + `/upload`, null)
            .toAugurHttpRequest();
    }
    uploadImageAndResize(): IAugurHttpRequest {
        
        return this.http.post(this.baseUrl + this.controllerRoute + `/uploadImageAndResize`, null)
            .toAugurHttpRequest();
    }
    uploadAudio(): IAugurHttpRequest {
        
        return this.http.post(this.baseUrl + this.controllerRoute + `/uploadAudio`, null)
            .toAugurHttpRequest();
    }
}