/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
export class ListeningQuestionAudioGridModel {
    id: number;
    title: string;
    language: string;
    level: string;
    author: string;
    organization: string;
    numberOfQuestions: number;
    approved: boolean;
    approvedBy: string;
    fileAdded: boolean;
}