/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { HttpClient, HttpParams, HttpResponse } from '@angular/common/http';
import { Inject, Injectable } from '@angular/core';
import { AugurHttpRequest, IAugurHttpRequest } from '@augur';
import { RegisterModel } from '@platform/web-api-controllers/identity/registration/models/register-model';
import { SignInResponseModel } from '@platform/models/sign-in-response-model';

@Injectable({
    providedIn: 'root'
})
export class RegistrationController {

    constructor(protected http: HttpClient, @Inject('BASE_URL')protected baseUrl: string) {
        
        this.register = this.register.bind(this);
    }

    controllerRoute: string = 'api/registration';
    
    register(model: RegisterModel): AugurHttpRequest<SignInResponseModel> {
        
        return this.http.post(this.baseUrl + this.controllerRoute + `/register`, model ? model : {})
            .toAugurHttpRequestWithValidation<SignInResponseModel>();
    }
}