/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
export enum ApiSystemEvent {
    LoggedInUserChanged = 1
}

export const ApiSystemEventDefinition = {
    1: {
        title: 'LoggedInUserChanged',
        value: ApiSystemEvent.LoggedInUserChanged
    }
}