/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
export enum EmailVerificationErrorType {
    InvalidCode = 1,
    MaximumAttemptsReached = 2
}

export const EmailVerificationErrorTypeDefinition = {
    1: {
        title: 'InvalidCode',
        value: EmailVerificationErrorType.InvalidCode
    },
    2: {
        title: 'MaximumAttemptsReached',
        value: EmailVerificationErrorType.MaximumAttemptsReached
    }
}