/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
export enum RoleType {
    Admin = 1,
    User = 2
}

export const RoleTypeDefinition = {
    1: {
        title: 'Admin',
        value: RoleType.Admin
    },
    2: {
        title: 'User',
        value: RoleType.User
    }
}