/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
 export enum DisseminationActivityType {
    FaceToFace = 0,
    InternetBased = 1,
    PaperBased = 2,
    Performance = 3
}