/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
export enum ListeningQuestionAnswerType {
    Text = 1,
    Image = 2
}

export const ListeningQuestionAnswerTypeDefinition = {
    1: {
        title: 'Text',
        value: ListeningQuestionAnswerType.Text
    },
    2: {
        title: 'Image',
        value: ListeningQuestionAnswerType.Image
    }
}