/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
export enum ReadingQuestionAnswerType {
    Text = 1,
    Image = 2
}

export const ReadingQuestionAnswerTypeDefinition = {
    1: {
        title: 'Text',
        value: ReadingQuestionAnswerType.Text
    },
    2: {
        title: 'Image',
        value: ReadingQuestionAnswerType.Image
    }
}