/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
export enum SingleAnswerQuestionAnswerType {
    Text = 1,
    Image = 2
}

export const SingleAnswerQuestionAnswerTypeDefinition = {
    1: {
        title: 'Text',
        value: SingleAnswerQuestionAnswerType.Text
    },
    2: {
        title: 'Image',
        value: SingleAnswerQuestionAnswerType.Image
    }
}