/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
export enum UseOfLanguageQuestionType {
    MultipleChoice = 1,
    SingleGap = 2,
    DragDrop = 3,
    SingleAnswer = 4
}

export const UseOfLanguageQuestionTypeDefinition = {
    1: {
        title: 'Multiple choice',
        value: UseOfLanguageQuestionType.MultipleChoice
    },
    2: {
        title: 'Single gap',
        value: UseOfLanguageQuestionType.SingleGap
    },
    3: {
        title: 'Drag and drop',
        value: UseOfLanguageQuestionType.DragDrop
    },
    4: {
        title: 'Single answer',
        value: UseOfLanguageQuestionType.SingleAnswer
    }
}