/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { HttpClient, HttpParams, HttpResponse } from '@angular/common/http';
import { Inject, Injectable } from '@angular/core';
import { AugurHttpRequest, IAugurHttpRequest } from '@augur';
import { EmailVerificationCodeModel } from '@platform/web-api-controllers/identity/email-verification/models/email-verification-code-model';
import { ConfirmEmailVerificationCodeResultModel } from '@platform/web-api-controllers/identity/email-verification/models/confirm-email-verification-code-result-model';
import { SendEmailVerificationCodeResultModel } from '@platform/web-api-controllers/identity/email-verification/models/send-email-verification-code-result-model';

@Injectable({
    providedIn: 'root'
})
export class EmailVerificationController {

    constructor(protected http: HttpClient, @Inject('BASE_URL')protected baseUrl: string) {
        
        this.confirmEmailVerificationCode = this.confirmEmailVerificationCode.bind(this);
        this.resendEmailVerificationCode = this.resendEmailVerificationCode.bind(this);
        this.sendEmailVerificationCode = this.sendEmailVerificationCode.bind(this);
    }

    controllerRoute: string = 'api/emailVerification';
    
    confirmEmailVerificationCode(model: EmailVerificationCodeModel): AugurHttpRequest<HttpResponse<ConfirmEmailVerificationCodeResultModel>> {
        
        return this.http.post(this.baseUrl + this.controllerRoute + `/confirmEmailVerificationCode`, model ? model : {}, { observe: 'response' })
            .toAugurHttpRequest<HttpResponse<ConfirmEmailVerificationCodeResultModel>>();
    }
    resendEmailVerificationCode(): AugurHttpRequest<SendEmailVerificationCodeResultModel> {
        
        return this.http.post(this.baseUrl + this.controllerRoute + `/resendEmailVerificationCode`, null)
            .toAugurHttpRequest<SendEmailVerificationCodeResultModel>();
    }
    sendEmailVerificationCode(): AugurHttpRequest<SendEmailVerificationCodeResultModel> {
        
        return this.http.post(this.baseUrl + this.controllerRoute + `/sendEmailVerificationCode`, null)
            .toAugurHttpRequest<SendEmailVerificationCodeResultModel>();
    }
}