/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { PermissionActivityModel } from '@platform/web-api-controllers/access-control/permissions/models/permission-activity-model';

export class PermissionComponentModel {
    name: string;
    isAllowed: boolean;
    activities: PermissionActivityModel[];
}