/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { ChangedPermissionModel } from '@platform/web-api-controllers/access-control/permissions/models/changed-permission-model';

export class UpdatePermissionsModel {
    roleId: number;
    permissions: ChangedPermissionModel[];
}