/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { HttpClient, HttpParams, HttpResponse } from '@angular/common/http';
import { Inject, Injectable } from '@angular/core';
import { AugurHttpRequest, IAugurHttpRequest } from '@augur';
import { RequestPasswordResetModel } from '@platform/web-api-controllers/identity/password-reset/models/request-password-reset-model';
import { SetNewPasswordModel } from '@platform/web-api-controllers/identity/password-reset/models/set-new-password-model';

@Injectable({
    providedIn: 'root'
})
export class PasswordResetController {

    constructor(protected http: HttpClient, @Inject('BASE_URL')protected baseUrl: string) {
        
        this.requestPasswordReset = this.requestPasswordReset.bind(this);
        this.setNewPassword = this.setNewPassword.bind(this);
    }

    controllerRoute: string = 'api/passwordReset';
    
    requestPasswordReset(model: RequestPasswordResetModel): IAugurHttpRequest {
        
        return this.http.post(this.baseUrl + this.controllerRoute + `/requestPasswordReset`, model ? model : {})
            .toAugurHttpRequest();
    }
    setNewPassword(model: SetNewPasswordModel): IAugurHttpRequest {
        
        return this.http.post(this.baseUrl + this.controllerRoute + `/setNewPassword`, model ? model : {})
            .toAugurHttpRequest();
    }
}