/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { UseOfLanguageQuestionType } from '@src/app/enums/use-of-language-question-type';

export class UseOfLanguageQuestionGridModel {
    id: number;
    title: string;
    language: string;
    level: string;
    author: string;
    organization: string;
    type: UseOfLanguageQuestionType;
    approved: boolean;
    approvedBy: string;
}