/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { HttpClient, HttpParams, HttpResponse } from '@angular/common/http';
import { Inject, Injectable } from '@angular/core';
import { AugurHttpRequest, IAugurHttpRequest } from '@augur';
import { SignInModel } from '@platform/web-api-controllers/identity/authentication/models/sign-in-model';
import { SignInResponseModel } from '@platform/models/sign-in-response-model';
import { LoggedInUserInfoModel } from '@platform/models/logged-in-user-info-model';

@Injectable({
    providedIn: 'root'
})
export class AuthenticationController {

    constructor(protected http: HttpClient, @Inject('BASE_URL')protected baseUrl: string) {
        
        this.signIn = this.signIn.bind(this);
        this.signOut = this.signOut.bind(this);
        this.getLoggedInUserInfo = this.getLoggedInUserInfo.bind(this);
    }

    controllerRoute: string = 'api/authentication';
    
    signIn(model: SignInModel): AugurHttpRequest<SignInResponseModel> {
        
        return this.http.post(this.baseUrl + this.controllerRoute + `/signIn`, model ? model : {})
            .toAugurHttpRequestWithValidation<SignInResponseModel>();
    }
    signOut(): IAugurHttpRequest {
        
        return this.http.post(this.baseUrl + this.controllerRoute + `/signOut`, null)
            .toAugurHttpRequest();
    }
    getLoggedInUserInfo(): AugurHttpRequest<LoggedInUserInfoModel> {
        
        return this.http.get(this.baseUrl + this.controllerRoute + `/getLoggedInUserInfo`)
            .toAugurHttpRequest<LoggedInUserInfoModel>();
    }
}