/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { HttpClient, HttpParams, HttpResponse } from '@angular/common/http';
import { Inject, Injectable } from '@angular/core';
import { AugurHttpRequest, IAugurHttpRequest } from '@augur';
import { MyProfileInfoModel } from '@src/app/web-api-controllers/my-profile/models/my-profile-info-model';

@Injectable({
    providedIn: 'root'
})
export class MyProfileController {

    constructor(protected http: HttpClient, @Inject('BASE_URL')protected baseUrl: string) {
        
        this.getMyProfileInfo = this.getMyProfileInfo.bind(this);
    }

    controllerRoute: string = 'api/myProfile';
    
    getMyProfileInfo(): AugurHttpRequest<MyProfileInfoModel> {
        
        return this.http.get(this.baseUrl + this.controllerRoute + `/getMyProfileInfo`)
            .toAugurHttpRequest<MyProfileInfoModel>();
    }
}