/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
export class CompleteReadingTestRequestModel {
    placementTestId: number;
    textId: number;
    totalAnswers: number;
    correctAnswers: number;
}