/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { UseOfLanguageQuestion } from '@src/app/entities/use-of-language-question';

export class PlacementTestQuestionsModel {
    questions: UseOfLanguageQuestion[];
}