/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { PlacementTestProgressQuestionModel } from '@src/app/web-api-controllers/placement-tests/models/placement-test-progress-question-model';

export class PlacementTestProgressModel {
    isCompleted: boolean;
    rating: number;
    rd: number;
    vol: number;
    placementTestId: number;
    questions: PlacementTestProgressQuestionModel[];
}