/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { IAugurEntityWithId } from '@augur';
export class GlobalSettings implements IAugurEntityWithId {
    
    constructor(init?: Partial<GlobalSettings>) {
        
        
        Object.assign(this, init);
    }
    
    id: number;
}