/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { IAugurEntityWithId } from '@augur';
import { User } from '@platform/entities/user';

export class Tenant implements IAugurEntityWithId {
    
    constructor(init?: Partial<Tenant>) {
        
        
        Object.assign(this, init);
    }
    
    orgOwner: User;
    orgOwnerId?: number;
    name: string;
    displayName: string;
    tenantId: number;
    id: number;
}