/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { IAugurEntityWithId } from '@augur';
import { AccountInfo } from '@platform/entities/account-info';
import { Tenant } from '@platform/entities/tenant';

export class User implements IAugurEntityWithId {
    
    constructor(init?: Partial<User>) {
        
        
        Object.assign(this, init);
    }
    
    isOrgAdmin: boolean;
    isSuperAdmin: boolean;
    hasVerifiedEmail: boolean;
    accountInfo: AccountInfo;
    userId: number;
    tenantId: number;
    tenant: Tenant;
    email: string;
    isActive: boolean;
    id: number;
}