/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
export class RegisterModel {
    email: string;
    password: string;
    tenantName: string;
    name: string;
    hasAcceptedTermsAndPrivacyPolicy: boolean;
}