/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { HttpClient, HttpParams, HttpResponse } from '@angular/common/http';
import { Inject, Injectable } from '@angular/core';
import { AugurHttpRequest, IAugurHttpRequest } from '@augur';
import { ChangePasswordModel } from '@platform/web-api-controllers/identity/change-password/models/change-password-model';

@Injectable({
    providedIn: 'root'
})
export class ChangePasswordController {

    constructor(protected http: HttpClient, @Inject('BASE_URL')protected baseUrl: string) {
        
        this.changePassword = this.changePassword.bind(this);
    }

    controllerRoute: string = 'api/changePassword';
    
    changePassword(model: ChangePasswordModel): IAugurHttpRequest {
        
        return this.http.post(this.baseUrl + this.controllerRoute + `/changePassword`, model ? model : {})
            .toAugurHttpRequestWithValidation();
    }
}