/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
export class Components {
    
     email = {
        _componentName: 'Email',
            bulkSend: {
                _componentName: 'Email',
                _activityName: 'BulkSend'
            }
    }
}