/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
export class UserUpdateModel {
    id: number;
    name: string;
    email: string;
    password: string;
    isOrgAdmin: boolean;
}