/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { HttpClient, HttpParams, HttpResponse } from '@angular/common/http';
import { Inject, Injectable } from '@angular/core';
import { AugurEntityController, AugurHttpRequest, IAugurHttpRequest } from '@augur';
import { UpdateNameModel } from '@src/app/web-api-controllers/account-infos/models/update-name-model';
import { AccountInfo } from '@platform/entities/account-info';

@Injectable({
    providedIn: 'root'
})
export class AccountInfosController extends AugurEntityController<AccountInfo> {

    constructor(protected http: HttpClient, @Inject('BASE_URL')protected baseUrl: string) {
        super('api/accountInfos', http, baseUrl);
        
        this.updateNameForLoggedInUser = this.updateNameForLoggedInUser.bind(this);
    }
    
    updateNameForLoggedInUser(model: UpdateNameModel): AugurHttpRequest<UpdateNameModel> {
        
        return this.http.post(this.baseUrl + this.controllerRoute + `/updateNameForLoggedInUser`, model ? model : {})
            .toAugurHttpRequest<UpdateNameModel>();
    }
}