/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { IAugurEntityWithId } from '@augur';
import { UseOfLanguageQuestionType } from '@src/app/enums/use-of-language-question-type';
import { Language } from '@src/app/entities/language';

export class Instruction implements IAugurEntityWithId {
    
    constructor(init?: Partial<Instruction>) {
        
        
        Object.assign(this, init);
    }
    
    text: string;
    questionType: UseOfLanguageQuestionType;
    language: Language;
    languageId: number;
    id: number;
}