/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { IAugurEntityWithId } from '@augur';
export class Level implements IAugurEntityWithId {
    
    constructor(init?: Partial<Level>) {
        
        
        Object.assign(this, init);
    }
    
    title: string;
    code: string;
    fromRating: number;
    rating: number;
    toRating: number;
    id: number;
}