/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { IAugurEntityWithId } from '@augur';
import { UploadedResource } from '@platform/entities/uploaded-resource';
import { ListeningQuestion } from '@src/app/entities/listening-question';

export class ListeningQuestionAnswer implements IAugurEntityWithId {
    
    constructor(init?: Partial<ListeningQuestionAnswer>) {
        
        
        Object.assign(this, init);
    }
    
    isCorrect: boolean;
    ordinal: number;
    text: string;
    image: UploadedResource;
    imageId?: number;
    question: ListeningQuestion;
    questionId: number;
    id: number;
}