/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { IAugurEntityWithId } from '@augur';
import { ListeningQuestionAnswerType } from '@src/app/enums/listening-question-answer-type';
import { ListeningQuestionAudio } from '@src/app/entities/listening-question-audio';
import { ListeningQuestionAnswer } from '@src/app/entities/listening-question-answer';
import { User } from '@platform/entities/user';
import { Tenant } from '@platform/entities/tenant';

export class ListeningQuestion implements IAugurEntityWithId {
    
    constructor(init?: Partial<ListeningQuestion>) {
        this.answers = [];
        
        Object.assign(this, init);
    }
    
    questionText: string;
    answerType: ListeningQuestionAnswerType;
    audio: ListeningQuestionAudio;
    audioId: number;
    answers: ListeningQuestionAnswer[];
    user: User;
    userId: number;
    tenant: Tenant;
    tenantId: number;
    id: number;
}