/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { IAugurEntityWithId } from '@augur';
export class MultipleChoiceQuestionTextPart implements IAugurEntityWithId {
    
    constructor(init?: Partial<MultipleChoiceQuestionTextPart>) {
        
        
        Object.assign(this, init);
    }
    
    text: string;
    id: number;
}