/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { IAugurEntityWithId } from '@augur';
import { MutlipleChoiceQuestionAnswerPartOption } from '@src/app/entities/mutliple-choice-question-answer-part-option';

export class MultipleChoiceQuestionAnswerPart implements IAugurEntityWithId {
    
    constructor(init?: Partial<MultipleChoiceQuestionAnswerPart>) {
        this.options = [];
        
        Object.assign(this, init);
    }
    
    options: MutlipleChoiceQuestionAnswerPartOption[];
    id: number;
}