/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { IAugurEntityWithId } from '@augur';
import { MultipleChoiceQuestionAnswerPart } from '@src/app/entities/multiple-choice-question-answer-part';

export class MutlipleChoiceQuestionAnswerPartOption implements IAugurEntityWithId {
    
    constructor(init?: Partial<MutlipleChoiceQuestionAnswerPartOption>) {
        
        
        Object.assign(this, init);
    }
    
    text: string;
    isCorrect: boolean;
    answerPart: MultipleChoiceQuestionAnswerPart;
    answerPartId: number;
    id: number;
}