/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { IAugurEntityWithId } from '@augur';
import { Language } from '@src/app/entities/language';
import { Level } from '@src/app/entities/level';
import { ReadingQuestionText } from '@src/app/entities/reading-question-text';
import { ListeningQuestionAudio } from '@src/app/entities/listening-question-audio';

export class PlacementTest implements IAugurEntityWithId {
    
    constructor(init?: Partial<PlacementTest>) {
        
        
        Object.assign(this, init);
    }
    
    rating: number;
    rd: number;
    vol: number;
    languageId: number;
    language: Language;
    startedOn: Date;
    completedOn?: Date;
    reportedLevel: Level;
    reportedLevelId?: number;
    shouldTestReading: boolean;
    shouldTestListening: boolean;
    readingTextCorrectAnswers?: number;
    readingTextTotalAnswers?: number;
    listeningAudioCorrectAnswers?: number;
    listeningAudioTotalAnswers?: number;
    readingQuestionTextId?: number;
    readingQuestionText: ReadingQuestionText;
    listeningQuestionAudioId?: number;
    listeningQuestionAudio: ListeningQuestionAudio;
    id: number;
}