/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { IAugurEntityWithId } from '@augur';
import { Language } from '@src/app/entities/language';
import { PlacementTest } from '@src/app/entities/placement-test';

export class PlacementTestInvitation implements IAugurEntityWithId {
    
    constructor(init?: Partial<PlacementTestInvitation>) {
        
        
        Object.assign(this, init);
    }
    
    email: string;
    token: string;
    hasGivenMarketingPermission: boolean;
    language: Language;
    languageId: number;
    placementTest: PlacementTest;
    placementTestId?: number;
    id: number;
}