/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { IAugurEntityWithId } from '@augur';
import { UseOfLanguageQuestion } from '@src/app/entities/use-of-language-question';
import { PlacementTest } from '@src/app/entities/placement-test';

export class PlacementTestQuestion implements IAugurEntityWithId {
    
    constructor(init?: Partial<PlacementTestQuestion>) {
        
        
        Object.assign(this, init);
    }
    
    rating: number;
    rd: number;
    vol: number;
    isAnsweredCorrectly: boolean;
    questionId: number;
    question: UseOfLanguageQuestion;
    placementTestId: number;
    placementTest: PlacementTest;
    id: number;
}