/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { IAugurEntityWithId } from '@augur';
import { User } from '@platform/entities/user';
import { Language } from '@src/app/entities/language';
import { Level } from '@src/app/entities/level';
import { Tenant } from '@platform/entities/tenant';
import { ReadingQuestion } from '@src/app/entities/reading-question';

export class ReadingQuestionText implements IAugurEntityWithId {
    
    constructor(init?: Partial<ReadingQuestionText>) {
        this.questions = [];
        
        Object.assign(this, init);
    }
    
    title: string;
    text: string;
    approved: boolean;
    user: User;
    userId: number;
    language: Language;
    languageId: number;
    level: Level;
    levelId: number;
    tenant: Tenant;
    tenantId: number;
    approver: User;
    approverId?: number;
    questions: ReadingQuestion[];
    id: number;
}