/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { IAugurEntityWithId } from '@augur';
import { SingleGapQuestionAnswer } from '@src/app/entities/single-gap-question-answer';
import { User } from '@platform/entities/user';
import { Tenant } from '@platform/entities/tenant';

export class SingleGapQuestion implements IAugurEntityWithId {
    
    constructor(init?: Partial<SingleGapQuestion>) {
        this.answers = [];
        
        Object.assign(this, init);
    }
    
    textBefore: string;
    textAfter: string;
    answers: SingleGapQuestionAnswer[];
    user: User;
    userId: number;
    tenant: Tenant;
    tenantId: number;
    id: number;
}