/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { IAugurEntityWithId } from '@augur';
import { UploadedResource } from '@platform/entities/uploaded-resource';
import { SingleAnswerQuestion } from '@src/app/entities/single-answer-question';

export class SingleAnswerQuestionAnswer implements IAugurEntityWithId {
    
    constructor(init?: Partial<SingleAnswerQuestionAnswer>) {
        
        
        Object.assign(this, init);
    }
    
    isCorrect: boolean;
    text: string;
    image: UploadedResource;
    imageId?: number;
    question: SingleAnswerQuestion;
    questionId: number;
    id: number;
}