/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { HttpClient, HttpParams, HttpResponse } from '@angular/common/http';
import { Inject, Injectable } from '@angular/core';
import { AugurHttpRequest, IAugurHttpRequest } from '@augur';
import { DashboardInfoModel } from '@src/app/web-api-controllers/dashboard/models/dashboard-info-model';

@Injectable({
    providedIn: 'root'
})
export class DashboardController {

    constructor(protected http: HttpClient, @Inject('BASE_URL')protected baseUrl: string) {
        
        this.getDashboardInfo = this.getDashboardInfo.bind(this);
    }

    controllerRoute: string = 'api/dashboard';
    
    getDashboardInfo(): AugurHttpRequest<DashboardInfoModel> {
        
        return this.http.get(this.baseUrl + this.controllerRoute + `/getDashboardInfo`)
            .toAugurHttpRequest<DashboardInfoModel>();
    }
}