/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { HttpClient, HttpParams, HttpResponse } from '@angular/common/http';
import { Inject, Injectable } from '@angular/core';
import { AugurHttpRequest, IAugurHttpRequest } from '@augur';
import { AugurEntityWithGridController, GridResult, GridRequestModel } from '@augur';
import { UseOfLanguageQuestionType } from '@src/app/enums/use-of-language-question-type';
import { Instruction } from '@src/app/entities/instruction';
import { InstructionGridModel } from '@src/app/web-api-controllers/instructions/models/instruction-grid-model';

@Injectable({
    providedIn: 'root'
})
export class InstructionsController extends AugurEntityWithGridController<Instruction, InstructionGridModel> {

    constructor(protected http: HttpClient, @Inject('BASE_URL')protected baseUrl: string) {
        super('api/instructions', http, baseUrl);
        
        this.listForQuestionTypeAndLanguage = this.listForQuestionTypeAndLanguage.bind(this);
    }
    
    listForQuestionTypeAndLanguage(languageId: number, questionType: UseOfLanguageQuestionType, pageNumber: number, pageSize: number, searchQuery: string, columnFilter: any): AugurHttpRequest<HttpResponse<any[]>> {
        const queryParams = new HttpParams()
            .set('languageId', languageId ? languageId.toString() : '')
            .set('questionType', questionType ? questionType.toString() : '')
            .set('pageNumber', pageNumber ? pageNumber.toString() : '')
            .set('pageSize', pageSize ? pageSize.toString() : '')
            .set('searchQuery', searchQuery ? searchQuery.toString() : '');
        
        return this.http.post(this.baseUrl + this.controllerRoute + `/listForQuestionTypeAndLanguage`, columnFilter ? columnFilter : {}, { params: queryParams, observe: 'response' })
            .toAugurHttpRequest<HttpResponse<any[]>>();
    }
}