/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { HttpClient, HttpParams, HttpResponse } from '@angular/common/http';
import { Inject, Injectable } from '@angular/core';
import { AugurHttpRequest, IAugurHttpRequest } from '@augur';
import { AugurEntityWithGridController, GridResult, GridRequestModel } from '@augur';
import { ListeningQuestion } from '@src/app/entities/listening-question';
import { ListeningQuestionGridModel } from '@src/app/web-api-controllers/listening-questions/models/listening-question-grid-model';

@Injectable({
    providedIn: 'root'
})
export class ListeningQuestionsController extends AugurEntityWithGridController<ListeningQuestion, ListeningQuestionGridModel> {

    constructor(protected http: HttpClient, @Inject('BASE_URL')protected baseUrl: string) {
        super('api/listeningQuestions', http, baseUrl);
        
        
    }
    
    
}