/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { HttpClient, HttpParams, HttpResponse } from '@angular/common/http';
import { Inject, Injectable } from '@angular/core';
import { AugurHttpRequest, IAugurHttpRequest } from '@augur';
import { AugurEntityWithGridController, GridResult, GridRequestModel } from '@augur';
import { ReadingQuestionText } from '@src/app/entities/reading-question-text';
import { ReadingQuestionTextGridModel } from '@src/app/web-api-controllers/reading-question-texts/models/reading-question-text-grid-model';

@Injectable({
    providedIn: 'root'
})
export class ReadingQuestionTextsController extends AugurEntityWithGridController<ReadingQuestionText, ReadingQuestionTextGridModel> {

    constructor(protected http: HttpClient, @Inject('BASE_URL')protected baseUrl: string) {
        super('api/readingQuestionTexts', http, baseUrl);
        
        this.toggleApproval = this.toggleApproval.bind(this);
    }
    
    toggleApproval(question: ReadingQuestionText): AugurHttpRequest<boolean> {
        
        return this.http.post(this.baseUrl + this.controllerRoute + `/toggleApproval`, question ? question : {})
            .toAugurHttpRequest<boolean>();
    }
}