/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { HttpClient, HttpParams, HttpResponse } from '@angular/common/http';
import { Inject, Injectable } from '@angular/core';
import { AugurHttpRequest, IAugurHttpRequest } from '@augur';
import { AugurEntityWithGridController, GridResult, GridRequestModel } from '@augur';
import { UseOfLanguageQuestion } from '@src/app/entities/use-of-language-question';
import { UseOfLanguageQuestionGridModel } from '@src/app/web-api-controllers/use-of-language-questions/models/use-of-language-question-grid-model';

@Injectable({
    providedIn: 'root'
})
export class UseOfLanguageQuestionsController extends AugurEntityWithGridController<UseOfLanguageQuestion, UseOfLanguageQuestionGridModel> {

    constructor(protected http: HttpClient, @Inject('BASE_URL')protected baseUrl: string) {
        super('api/useOfLanguageQuestions', http, baseUrl);
        
        this.toggleApproval = this.toggleApproval.bind(this);
    }
    
    toggleApproval(question: UseOfLanguageQuestion): AugurHttpRequest<boolean> {
        
        return this.http.post(this.baseUrl + this.controllerRoute + `/toggleApproval`, question ? question : {})
            .toAugurHttpRequest<boolean>();
    }
}