/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { HttpClient, HttpParams, HttpResponse } from '@angular/common/http';
import { Inject, Injectable } from '@angular/core';
import { AugurHttpRequest, IAugurHttpRequest } from '@augur';
import { AugurEntityWithGridController, GridResult, GridRequestModel } from '@augur';
import { ReadingQuestion } from '@src/app/entities/reading-question';
import { ReadingQuestionGridModel } from '@src/app/web-api-controllers/reading-questions/models/reading-question-grid-model';

@Injectable({
    providedIn: 'root'
})
export class ReadingQuestionsController extends AugurEntityWithGridController<ReadingQuestion, ReadingQuestionGridModel> {

    constructor(protected http: HttpClient, @Inject('BASE_URL')protected baseUrl: string) {
        super('api/readingQuestions', http, baseUrl);
        
        
    }
    
    
}