/*
    This is an autogenerated file.
    Remove this comment if you don't want your changes to this file to be overwritten.
*/
import { AccountInfoModel } from '@src/app/web-api-controllers/my-profile/models/account-info-model';

export class MyProfileInfoModel {
    accountInfo: AccountInfoModel;
}